# sources.yml
schema_version: "1.0"
mcp_name: "Malaysian Law MCP"
jurisdiction: "MY"

sources:
  - name: "Attorney General's Chambers - Federal Legislation Portal"
    authority: "Attorney General's Chambers of Malaysia (Jabatan Peguam Negara)"
    official_portal: "https://www.agc.gov.my"
    canonical_identifier: "N/A (Malaysian legislation identified by Act number and year, e.g., 'Act 709')"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A (structured web portal with browse and search functionality)"
    update_frequency: "weekly"
    last_ingested: "PENDING_FIRST_INGEST"
    license_or_terms:
      type: "Government Open Data"
      url: "https://www.agc.gov.my"
      summary: "Official repository of Malaysian federal legislation maintained by the Attorney General's Chambers; provides access to Acts of Parliament, subsidiary legislation, and the Federal Constitution; government legislation is publicly accessible"
    coverage:
      scope: "All Acts of Parliament including the Personal Data Protection Act 2010 (Act 709), Computer Crimes Act 1997 (Act 563), Communications and Multimedia Act 1998 (Act 588), Companies Act 2016 (Act 777), Electronic Commerce Act 2006 (Act 658), Strategic Trade Act 2010, and the Federal Constitution; subsidiary legislation and regulations"
      limitations: "Some subsidiary legislation may not be immediately updated after amendment; legislation is available in both Malay and English but amendments may appear in one language before the other; historical consolidated versions may have limited availability"
    languages:
      - "ms"
      - "en"

  - name: "Malaysian Laws Portal (CommonLII)"
    authority: "CommonLII / Malaysian government sources"
    official_portal: "https://www.commonlii.org/my/legis/"
    canonical_identifier: "N/A"
    retrieval_method: "HTML_SCRAPE"
    api_documentation: "N/A"
    update_frequency: "monthly"
    last_ingested: "PENDING_FIRST_INGEST"
    license_or_terms:
      type: "Open Access"
      url: "https://www.commonlii.org/my/legis/"
      summary: "Commonwealth Legal Information Institute mirror of Malaysian legislation; supplementary source for consolidated versions and historical Acts"
    coverage:
      scope: "Malaysian federal Acts of Parliament, selected subsidiary legislation, and constitutional provisions; useful for historical and consolidated versions"
      limitations: "May not reflect the most recent amendments; supplementary source only; not an official government portal"
    languages:
      - "en"
      - "ms"

data_freshness:
  automated_checks: true
  check_frequency: "weekly"
  last_verified: "PENDING_FIRST_INGEST"

# Notes:
# - Malaysia uses a mixed legal system combining common law (inherited from British colonial
#   rule), Islamic law (Syariah, applicable to Muslims for personal matters), and customary
#   law (adat)
# - The Federal Constitution is the supreme law of Malaysia; Article 5 protects personal liberty
# - The PDPA 2010 (Act 709) was one of the first comprehensive data protection laws in Asia;
#   it does NOT apply to federal and state governments (a notable exclusion)
# - The PDP Commissioner (Jabatan Perlindungan Data Peribadi) under the Ministry of
#   Communications and Digital is the supervisory authority for the PDPA
# - Recent amendments to the PDPA (2024) expand scope and strengthen enforcement including
#   mandatory data breach notification
# - The Computer Crimes Act 1997 (Act 563) covers unauthorised access, interception, and
#   modification of computer systems
# - The Communications and Multimedia Act 1998 (Act 588) regulates the converging
#   telecommunications, broadcasting, and online industries
# - Malaysia uses the Act numbering system (e.g., Act 709 = PDPA 2010)
# - Legislation is available in both Malay (Bahasa Melayu) and English; the Malay text
#   prevails in case of conflict (National Language Act 1963/67)
# - Malaysia is an ASEAN member and participates in the ASEAN Framework on Personal Data
#   Protection and the ASEAN Digital Data Governance Framework
